### ISSUE TITLE
re-org

### ISSUE THREAD

**Issue by amaloney** [holoviz-topics/holoSeq#1]
Reorganize the repo for easy installation.

### `TODO`

- [x] Move documentation to a `docs` folder
- [x] Move Jupyter notebooks to a `notebooks` folder
- [x] Move `*.gz` and `*.len` files to a `data` folder
- [x] Add a `conda` environment file
- [x] Add a `pyproject.toml` file
- [x] Create an installable package
- [x] Move script files to a `scripts` folder.
- [ ] Update the data loader to include new data checks
- [ ] Follow the `holoseq_display.py` script to create a visualization using available data
